name: on_push_development

on:
  pull_request:
    branches:
      - 'development'
  push:
    branches:
      - "development"
      - "unit_test"
      - "feature/*"

jobs:
  unit-test:
    name: "unit test - run unit test on action"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Running Unit-Test
        run: go test ./... -cover